export const TIME = {
  DEFAULT_BOOKING_DURATION_MINUTES: 120,
  MILLISECONDS_PER_MINUTE: 60000,
  END_OF_DAY: {
    HOURS: 23,
    MINUTES: 59,
    SECONDS: 59,
    MILLISECONDS: 999,
  },
} as const;
