export const TIME = {
  DEFAULT_BOOKING_DURATION_MINUTES: 120,
  MILLISECONDS_PER_MINUTE: 60000,
  END_OF_DAY: {
    HOURS: 23,
    MINUTES: 59,
    SECONDS: 59,
    MILLISECONDS: 999,
  },
  DEFAULT_SLOT_DURATION_MINUTES: 60,
  WORK_HOURS: {
    START: 5,
    END: 18,
  },
} as const;
